services:
  - type: web
    name: selfbot
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: SECRET_MASTER_PASSWORD
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: true
